[package]
name = "glimpse-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
anyhow = { workspace = true }
dirs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
