[package]
name = "glimpse-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
tokio = { version = "1.47.0", features = ["net", "sync"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
