[package]
name = "glimpsed"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
tokio = "1.47.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
glimpse-sdk = { path = "../glimpse-sdk" }
