[package]
name = "glimpse"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
numbat = "1.16.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
iced = { version = "0.13.1", features = ["tokio", "image", "svg"] }
tokio = { version = "1.46.1", features = ["fs", "process"] }


[[bin]]
name = "glimpse"
path = "src/main.rs"
