[package]
name = "glimpse"
version = "0.1.0"
edition = "2024"

[dependencies]
glib = "0.20.12"
gtk = { version = "0.9.7", package = "gtk4" }
adw = { version = "0.7", package = "libadwaita", features = ["v1_7"] }
glimpse-sdk = { path = "./glimpse-sdk" }
gio = "0.20.12"
meval = "0.2.0"
dbus = "0.9.7"
log = "0.4.27"

[build-dependencies]
glib-build-tools = "0.19"
glob = "0.3.2"

[[bin]]
name = "glimpse"
path = "src/main.rs"

[dev-dependencies]
glib-build-tools = "0.19"
