[package]
name = "glimpse-widgets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
gio.workspace = true
glib.workspace = true
gtk4.workspace = true
tracing.workspace = true

[dev-dependencies]
adw.workspace = true

[build-dependencies]
glib-build-tools.workspace = true
