[build-system]
requires = ["uv_build>=0.5,<0.20"]
build-backend = "uv_build"

[project]
name = "colorpicker"
version = "0.1.0"
description = "A Glimpse exec applet."
requires-python = ">=3.14"
dependencies = [
    "glimpse-applet-sdk>=0.2,<1",
]

[tool.uv.build-backend]
module-name = "colorpicker"
module-root = ""

[tool.uv.sources]
glimpse-sdk = { path = "../../sdk/sdk-py", editable = true }
glimpse-applet-sdk = { path = "../../sdk/sdk-py", editable = true }
