[package]
name = "calculator"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.0", features = ["io-util", "macros", "net"] }
glimpse-sdk = { path = "../../glimpse-sdk" }
numbat = "1.16.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
