[package]
name = "glimpse-plugins-calculator"
version = "0.1.0"
edition = "2024"

[dependencies]
numbat = "1.16.0"
tokio = { workspace = true }
glimpse-sdk = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
