[package]
name = "glimpse-panel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
adw.workspace = true
anstream.workspace = true
anyhow.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
clap.workspace = true
colorchoice-clap.workspace = true
futures-util.workspace = true
gettext-rs.workspace = true
gio.workspace = true
gio-unix.workspace = true
glib.workspace = true
glimpse-config.workspace = true
glimpse-dbus.workspace = true
glimpse-services.workspace = true
glimpse-utils.workspace = true
glimpse-widgets.workspace = true
gtk4.workspace = true
gtk4-layer-shell.workspace = true
owo-colors.workspace = true
relm4.workspace = true
shadow-rs.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
wayland-client.workspace = true
wayland-protocols.workspace = true
wayland-protocols-wlr.workspace = true
zeroize.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
glib-build-tools.workspace = true
shadow-rs.workspace = true
