[package]
name = "glimpse-panel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anstream.workspace = true
anyhow.workspace = true
clap.workspace = true
glimpse-config = { path = "../glimpse-config" }
glimpse-ipc = { path = "../glimpse-ipc" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
