[package]
name = "glimpse-services"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chrono-tz.workspace = true
chrono.workspace = true
dirs.workspace = true
futures-util.workspace = true
gio-unix.workspace = true
glimpse-compositors.workspace = true
glimpse-config.workspace = true
glimpse-contracts.workspace = true
glimpse-dbus.workspace = true
glimpse-utils.workspace = true
icalendar.workspace = true
iso8601.workspace = true
regex.workspace = true
reqwest.workspace = true
reverse_geocoder.workspace = true
rrule.workspace = true
serde.workspace = true
serde_json.workspace = true
sunrise.workspace = true
thiserror.workspace = true
tokio-util.workspace = true
tokio.workspace = true
tracing.workspace = true
tzf-rs.workspace = true
url.workspace = true
zbus.workspace = true

[dev-dependencies]
tempfile.workspace = true
