[package]
name = "glimpse-plugins-echo"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
glimpse-sdk = { workspace = true }
tracing = { workspace = true }
async-trait = "0.1.89"
