[package]
name = "glimpse-plugins-apps"
version = "0.1.0"
edition = "2024"

[dependencies]
glimpse-sdk = { workspace = true }
gio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
freedesktop-icons = { workspace = true }
freedesktop-desktop-entry = { workspace = true }
