[package]
name = "sunset"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
async-trait = "0.1"
glimpse-core = { path = "../../glimpse-core" }
glimpse-sdk = { path = "../../sdk/sdk-rs" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
chrono = "0.4"

[dev-dependencies]
serde_json = "1"
